; sample configuration
# Written by Giarri
host = localhost
port = 5432
debug=true
timeout=30
key=key
[foo]
[[bar]]
test=true
[section]
key = value
debug=true
[[color]]
red=roses are red
[[foo]]
bar=false
