name: CI test on ubuntu

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build

      - name: Build and install the library
        run: cmake --build build/ini_resource_lib --verbose &&
             sudo cmake --install build/ini_resource_lib --verbose

      - name: Build the other targets
        run: cmake --build build

      - name: Test
        run: ./test.sh
